import type { Metadata } from "next"
import Lenis from "./components/Lenix"
import "./globals.css"
import { trap } from "@/utils/fonts"

export const metadata: Metadata = {
	title: "Milind's Portfolio",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${trap.variable} font-trap min-h-screen grid *:[grid-area:1/-1]`}
			>
				<Lenis>{children}</Lenis>
			</body>
		</html>
	)
}
