import type { Metadata } from "next"
import Lenis from "../components/Lenix"
import "./globals.css"
import { trap } from "@/utils/fonts"
import { Provider } from "jotai"
import GridBackground from "@/components/GridBackground"
import SideNav from "@/components/SideNav"
import TransitionSlider from "@/components/TransitionSlider"

export const metadata: Metadata = {
	title: "Milind's Portfolio",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${trap.variable} font-trap min-h-screen grid *:[grid-area:1/-1]`}
			>
				<Provider>
					<Lenis>
						<GridBackground />
						<div className="gridBgFade | h-screen sticky top-0 z-10"></div>
						<div className="wrapper | z-20 max-w-screen-[1440px] relative">
							<SideNav />
							<TransitionSlider>{children}</TransitionSlider>
						</div>
					</Lenis>
				</Provider>
			</body>
		</html>
	)
}
